"""Removable simulated capture sets for cold-start development.

Technical plan §5.4d keeps simulated data as an open option, valued for exactly
two things: cold start — a trainable model before the first self-measured site
is booked — and rare conditions that are expensive to wait for in the field.

Everything this module produces is disposable by construction. A seed set lives
under its own directory, carries a marker file, and tags every capture
``origin="simulated"`` so the §11 leak test catches it if it is ever routed
somewhere it should not be. Nothing here is ground truth and nothing here may
appear in an accuracy figure.

The generator is deliberately crude — it produces records, not images. Whether
BIM-derived renders transfer to real electrical rough-in photos is an open
question §13.6 wants answered by a timeboxed evaluation, not assumed by us here.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from random import Random

from .datasets import SIMULATED, Capture

__all__ = [
    "SEED_MARKER",
    "SeedSet",
    "generate_seed_captures",
    "load_seed_captures",
    "purge_seed_data",
]

#: Written into every seed directory. ``purge_seed_data`` refuses to delete a
#: directory without it, so a mistyped path removes nothing.
SEED_MARKER = ".sitewire-seed"

_TRADES = ("electrical_rough_in", "concrete_forming")
_AREAS = ("level-1-north", "level-1-south", "level-2-core", "level-3-west")

#: Conditions §5.4d calls out as the expensive-to-wait-for cases — the ones
#: where abstention behaviour actually matters.
_CONDITIONS = ("normal", "low_light", "partial_occlusion", "oblique_angle", "dust")


@dataclass(frozen=True)
class SeedSet:
    """A generated, removable set of simulated captures."""

    path: Path
    captures: list[Capture]

    def __len__(self) -> int:
        return len(self.captures)


def generate_seed_captures(
    dest: Path | str,
    count: int = 50,
    *,
    trade: str = "electrical_rough_in",
    seed: int = 0,
) -> SeedSet:
    """Generate ``count`` simulated captures under ``dest`` and return them.

    ``seed`` fixes the RNG so a given call is reproducible — a fixture that
    changes shape between runs makes failures impossible to read. Overwrites any
    existing seed set at ``dest``; refuses to overwrite a directory that is not
    one, on the same marker check ``purge_seed_data`` uses.
    """
    if count < 1:
        raise ValueError(f"count must be at least 1, got {count}")
    if trade not in _TRADES:
        raise ValueError(f"unknown trade {trade!r}; expected one of {list(_TRADES)}")

    dest = Path(dest)
    if dest.exists():
        _require_marker(dest)
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    rng = Random(seed)
    captures = [
        Capture(
            capture_id=f"sim-{trade}-{i:04d}",
            origin=SIMULATED,
            project_id=f"sim-project-{seed}",
            scope_item_id=f"sim-scope-{rng.randrange(1, 12):03d}",
        )
        for i in range(count)
    ]

    records = [
        {
            **asdict(c),
            "trade": trade,
            "area": rng.choice(_AREAS),
            "condition": rng.choice(_CONDITIONS),
        }
        for c in captures
    ]

    (dest / SEED_MARKER).write_text(
        "Generated by quantity_ml.seed. Simulated data — training only, never\n"
        "measurement (technical plan §5.4d). Safe to delete at any time.\n",
        encoding="utf-8",
    )
    (dest / "captures.json").write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8")
    return SeedSet(path=dest, captures=captures)


def load_seed_captures(dest: Path | str) -> list[Capture]:
    """Read back a generated seed set as ``Capture`` records."""
    dest = Path(dest)
    _require_marker(dest)
    records = json.loads((dest / "captures.json").read_text(encoding="utf-8"))
    return [
        Capture(
            capture_id=r["capture_id"],
            origin=r["origin"],
            project_id=r["project_id"],
            scope_item_id=r["scope_item_id"],
        )
        for r in records
    ]


def purge_seed_data(dest: Path | str) -> int:
    """Delete a seed set. Returns the number of files removed.

    Refuses any directory without the marker file, so this can never be pointed
    at real capture storage. Returns 0 for a path that does not exist — purging
    nothing is a fine outcome for a teardown step.
    """
    dest = Path(dest)
    if not dest.exists():
        return 0
    _require_marker(dest)
    removed = sum(1 for p in dest.rglob("*") if p.is_file())
    shutil.rmtree(dest)
    return removed


def _require_marker(dest: Path) -> None:
    if not dest.is_dir():
        raise NotADirectoryError(f"{dest} is not a directory")
    if not (dest / SEED_MARKER).exists():
        raise ValueError(
            f"{dest} has no {SEED_MARKER} marker — refusing to treat it as removable "
            "seed data. Only directories created by generate_seed_captures may be purged."
        )
