/**
 * Where corpus bytes actually live.
 *
 * The trainer keeps working on a local directory and gains the option of an S3
 * bucket behind the same four operations. Both backends store the identical key
 * layout — `samples/<id>.json`, `images/<id>.jpg`, `exports/<cut>/…` — so a corpus
 * is the same shape whether it is on a laptop or in `ca-central-1`, and moving one
 * to the other is a copy rather than a migration.
 *
 * Four operations, deliberately: list, get, put, remove. Anything richer (a query,
 * an index, a transaction) would be a capability the filesystem backend has to
 * fake, and the moment the two backends can do different things, the app quietly
 * starts depending on whichever it was developed against.
 *
 * Residency note: the S3 backend refuses a non-Canadian region outright. Business
 * plan §4.3 makes residency contractual, and a default region picked up from an
 * ambient environment variable is exactly how media ends up in Ohio.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

export interface CorpusBackend {
  /** Human-readable location, shown in the header so it is never a mystery. */
  describe(): string;
  /** Keys under a prefix. Returns keys, not paths — the caller never sees a path. */
  list(prefix: string): Promise<string[]>;
  get(key: string): Promise<Buffer | null>;
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  remove(key: string): Promise<void>;
}

/**
 * Keys are generated by this app, never taken from a request — but the check is
 * here anyway, because that sentence has been true right up until the day someone
 * adds an import feature.
 */
const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9._/-]{0,300}$/;

export function assertSafeKey(key: string): void {
  if (!SAFE_KEY.test(key) || key.includes("..")) {
    throw new Error(`refusing an unusable corpus key: ${key}`);
  }
}

// ---- filesystem -----------------------------------------------------------

/**
 * A plain directory.
 *
 * Writes go through a temp file and a rename. A half-written sample file is the
 * one failure that would cost a labelling session, and rename is atomic enough on
 * every platform this runs on to make that impossible.
 */
export function fsBackend(root: string): CorpusBackend {
  const base = resolve(root);

  const pathFor = (key: string): string => {
    assertSafeKey(key);
    const full = resolve(base, key);
    // Containment by resolution rather than by filtering "..", which misses
    // encodings and symlinks.
    if (full !== base && !full.startsWith(base + sep)) {
      throw new Error(`refusing a corpus key outside the store: ${key}`);
    }
    return full;
  };

  return {
    describe: () => base,

    list: async (prefix) => {
      const dir = resolve(base, prefix);
      if (!existsSync(dir)) return [];
      const keys: string[] = [];
      const walk = (current: string): void => {
        for (const entry of readdirSync(current, { withFileTypes: true })) {
          const full = join(current, entry.name);
          if (entry.isDirectory()) walk(full);
          else keys.push(relative(base, full).split(sep).join("/"));
        }
      };
      walk(dir);
      return keys;
    },

    get: async (key) => {
      const path = pathFor(key);
      return existsSync(path) ? readFileSync(path) : null;
    },

    put: async (key, bytes) => {
      const path = pathFor(key);
      mkdirSync(dirname(path), { recursive: true });
      const tmp = `${path}.tmp`;
      writeFileSync(tmp, bytes);
      renameSync(tmp, path);
    },

    remove: async (key) => {
      const path = pathFor(key);
      if (existsSync(path)) rmSync(path);
    },
  };
}

// ---- S3 -------------------------------------------------------------------

/**
 * The SDK is imported lazily so the filesystem path never pays for it — the local
 * case is the common one, and a labelling tool that takes an extra second to boot
 * because of a cloud client it is not using is a small daily tax for no benefit.
 */
async function s3Client(region: string) {
  const { S3Client } = await import("@aws-sdk/client-s3");
  return new S3Client({ region });
}

export interface S3Location {
  bucket: string;
  /** Always either empty or ending in "/". */
  prefix: string;
  region: string;
}

/** Parses `s3://bucket/optional/prefix`. */
export function parseS3Uri(uri: string, region: string): S3Location | null {
  const match = /^s3:\/\/([a-z0-9][a-z0-9.-]{1,61}[a-z0-9])(?:\/(.*))?$/.exec(uri.trim());
  if (!match) return null;
  const bucket = match[1];
  if (!bucket) return null;
  const raw = (match[2] ?? "").replace(/^\/+/, "").replace(/\/+$/, "");
  return { bucket, prefix: raw ? `${raw}/` : "", region };
}

export function s3Backend(location: S3Location): CorpusBackend {
  if (!/^ca-/.test(location.region)) {
    // Residency is contractual (business plan §4.3, technical plan §8). This is
    // the last place it can be enforced before real jobsite photos are uploaded.
    throw new Error(
      `refusing to store jobsite media in ${location.region}: Canadian residency is ` +
        "contractual — set AWS_REGION to a ca-* region.",
    );
  }

  const full = (key: string): string => {
    assertSafeKey(key);
    return location.prefix + key;
  };

  return {
    describe: () => `s3://${location.bucket}/${location.prefix} (${location.region})`,

    list: async (prefix) => {
      const { ListObjectsV2Command } = await import("@aws-sdk/client-s3");
      const client = await s3Client(location.region);
      const keys: string[] = [];
      let token: string | undefined;

      do {
        const page = await client.send(
          new ListObjectsV2Command({
            Bucket: location.bucket,
            Prefix: location.prefix + prefix,
            ...(token ? { ContinuationToken: token } : {}),
          }),
        );
        for (const object of page.Contents ?? []) {
          if (object.Key) keys.push(object.Key.slice(location.prefix.length));
        }
        token = page.IsTruncated ? page.NextContinuationToken : undefined;
      } while (token);

      return keys;
    },

    get: async (key) => {
      const { GetObjectCommand } = await import("@aws-sdk/client-s3");
      const client = await s3Client(location.region);
      try {
        const result = await client.send(
          new GetObjectCommand({ Bucket: location.bucket, Key: full(key) }),
        );
        const bytes = await result.Body?.transformToByteArray();
        return bytes ? Buffer.from(bytes) : null;
      } catch (err) {
        if (isNotFound(err)) return null;
        throw err;
      }
    },

    put: async (key, bytes, contentType) => {
      const { PutObjectCommand } = await import("@aws-sdk/client-s3");
      const client = await s3Client(location.region);
      await client.send(
        new PutObjectCommand({
          Bucket: location.bucket,
          Key: full(key),
          Body: bytes,
          ContentType: contentType,
          // Belt and braces: the bucket enforces encryption too, but a corpus that
          // is only encrypted because of a bucket setting is one console click from
          // not being.
          ServerSideEncryption: "AES256",
        }),
      );
    },

    remove: async (key) => {
      const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
      const client = await s3Client(location.region);
      await client.send(new DeleteObjectCommand({ Bucket: location.bucket, Key: full(key) }));
    },
  };
}

function isNotFound(err: unknown): boolean {
  if (typeof err !== "object" || err === null) return false;
  const name = (err as { name?: unknown }).name;
  const status = (err as { $metadata?: { httpStatusCode?: number } }).$metadata?.httpStatusCode;
  return name === "NoSuchKey" || name === "NotFound" || status === 404;
}

// ---- selection ------------------------------------------------------------

/**
 * Chooses a backend from the environment.
 *
 *   SITEWIREAI_TRAINER_STORE=s3://sitewireai-dev-corpus/corpus   → S3
 *   SITEWIREAI_TRAINER_STORE=D:/sitewireai-corpus                → that directory
 *   SITEWIREAI_TRAINER_DATA=D:/sitewireai-corpus                 → same, older name
 *   (nothing set)                                                → apps/trainer/data
 *
 * A malformed `s3://` URI throws rather than falling back to a local directory.
 * Silently writing a corpus somewhere other than where it was asked to go is the
 * kind of helpfulness that loses a day of labelling.
 */
export function backendFromEnv(env: NodeJS.ProcessEnv, defaultRoot: string): CorpusBackend {
  const configured = env.SITEWIREAI_TRAINER_STORE?.trim();

  if (configured?.startsWith("s3://")) {
    const region = env.AWS_REGION ?? env.AWS_DEFAULT_REGION ?? "ca-central-1";
    const location = parseS3Uri(configured, region);
    if (!location) throw new Error(`could not read SITEWIREAI_TRAINER_STORE: ${configured}`);
    return s3Backend(location);
  }

  return fsBackend(configured || env.SITEWIREAI_TRAINER_DATA?.trim() || defaultRoot);
}
