/**
 * Storage: a plain directory on this machine.
 *
 * This replaces a dual local/S3 backend with region enforcement, a bucket module
 * in Terraform, and an in-memory metadata index built at boot. None of it is
 * needed now — there is no corpus to share with a training job and no second
 * consumer to read it.
 *
 *   <store>/images/<id>.jpg    the photograph as uploaded
 *   <store>/photos/<id>.json   its record
 *
 * Point `SITEWIREAI_STORE` somewhere else to move it; the default sits beside the
 * app so a fresh clone works with no configuration.
 *
 * **Photos are stored exactly as uploaded.** Face redaction was removed by an
 * explicit product decision. There is no mosaicking step and no in-browser
 * pre-processing, so an image here contains whatever the camera captured,
 * including identifiable people, and the same bytes are sent to the model API
 * during classification. Anyone reintroducing a privacy claim to this product
 * needs to start by changing that, not by changing the copy.
 */

import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { type Photo, parsePhoto } from "./photo.js";

const HERE = dirname(fileURLToPath(import.meta.url));

const ROOT = resolve(process.env.SITEWIREAI_STORE ?? join(HERE, "..", "data"));
const IMAGES = join(ROOT, "images");
const PHOTOS = join(ROOT, "photos");

/**
 * The legacy record directory.
 *
 * The training build wrote records to `samples/`. They are still readable — see
 * `parsePhoto` — so they are listed from where they already are rather than
 * migrated. New records go to `photos/`.
 */
const LEGACY_PHOTOS = join(ROOT, "samples");

const EXTENSIONS: Record<string, string> = {
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/webp": ".webp",
};

export function extensionFor(mime: string): string | null {
  return EXTENSIONS[mime] ?? null;
}

export function mediaTypeFor(file: string): "image/jpeg" | "image/png" | "image/webp" {
  if (file.endsWith(".png")) return "image/png";
  if (file.endsWith(".webp")) return "image/webp";
  return "image/jpeg";
}

export function storeLocation(): string {
  return ROOT;
}

export function newId(): string {
  return randomUUID();
}

export async function openStore(): Promise<void> {
  await mkdir(IMAGES, { recursive: true });
  await mkdir(PHOTOS, { recursive: true });
}

/**
 * Guards a caller-supplied name into a file inside one of our directories.
 *
 * Every path that reaches the filesystem goes through here. The rule is narrow on
 * purpose: an id or image name is ours, generated by `randomUUID`, so anything
 * outside that alphabet is a request to go somewhere it should not.
 */
function safeName(name: string): string | null {
  return /^[A-Za-z0-9._-]+$/.test(name) && !name.includes("..") ? name : null;
}

export async function listPhotos(): Promise<Photo[]> {
  const photos: Photo[] = [];

  for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
    if (!existsSync(dir)) continue;
    for (const file of await readdir(dir)) {
      if (!file.endsWith(".json")) continue;
      try {
        const parsed = parsePhoto(JSON.parse(await readFile(join(dir, file), "utf8")));
        // A record already read from `photos/` wins over a legacy copy.
        if (parsed && !photos.some((p) => p.id === parsed.id)) photos.push(parsed);
      } catch {
        // A hand-edited file that no longer parses should not take the library
        // down with it. It is skipped and the rest of the corpus still lists.
      }
    }
  }

  return photos.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getPhoto(id: string): Promise<Photo | null> {
  const name = safeName(id);
  if (!name) return null;

  for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
    const path = join(dir, `${name}.json`);
    if (!existsSync(path)) continue;
    try {
      return parsePhoto(JSON.parse(await readFile(path, "utf8")));
    } catch {
      return null;
    }
  }
  return null;
}

export async function putPhoto(photo: Photo): Promise<void> {
  const name = safeName(photo.id);
  if (!name) throw new Error(`refusing to write a photo with an unusable id: ${photo.id}`);
  await writeFile(join(PHOTOS, `${name}.json`), JSON.stringify(photo, null, 2), "utf8");
}

export async function deletePhoto(id: string): Promise<boolean> {
  const name = safeName(id);
  if (!name) return false;

  const photo = await getPhoto(id);
  if (!photo) return false;

  for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
    const path = join(dir, `${name}.json`);
    if (existsSync(path)) await unlink(path);
  }

  const image = safeName(photo.imageFile);
  if (image && existsSync(join(IMAGES, image))) await unlink(join(IMAGES, image));
  return true;
}

export async function writeImage(file: string, bytes: Buffer): Promise<void> {
  const name = safeName(file);
  if (!name) throw new Error(`refusing to write an image with an unusable name: ${file}`);
  await writeFile(join(IMAGES, name), bytes);
}

export async function readImage(file: string): Promise<Buffer | null> {
  const name = safeName(file);
  if (!name) return null;
  const path = join(IMAGES, name);
  if (!existsSync(path)) return null;
  try {
    return await readFile(path);
  } catch {
    return null;
  }
}
