/**
 * Storage, with two backends behind one interface.
 *
 *   local  — a directory on this machine. The default, and what `pnpm serve` uses.
 *   aws    — DynamoDB for records, S3 for image bytes. Used when `SITEWIREAI_TABLE`
 *            is set, which is how the Lambda is configured.
 *
 * The switch is an environment variable rather than a build flag so the same
 * bundle runs in both places and local development needs no AWS credentials.
 *
 * **Images are addressed by URL, not by bytes.** `imageUrl()` returns a path the
 * browser fetches directly: `/images/<file>` locally, a presigned S3 URL in the
 * cloud. That is not a micro-optimisation — a Lambda response is capped at 6 MB
 * and these are multi-megabyte photographs, so proxying them through the function
 * would fail on exactly the large images most worth looking at.
 *
 * **Photos are stored exactly as uploaded.** Face redaction was removed by an
 * explicit product decision. Both backends hold whatever the camera captured,
 * including identifiable people. The S3 bucket is private and the app is behind
 * basic auth; those two facts are the only thing standing in front of these
 * images, so neither should be removed casually.
 */

import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import {
  DeleteCommand,
  DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
  ScanCommand,
} from "@aws-sdk/lib-dynamodb";
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { type Photo, parsePhoto } from "./photo.js";

const HERE = dirname(fileURLToPath(import.meta.url));

const TABLE = process.env.SITEWIREAI_TABLE ?? "";
const BUCKET = process.env.SITEWIREAI_BUCKET ?? "";

export function usingAws(): boolean {
  return Boolean(TABLE && BUCKET);
}

const EXTENSIONS: Record<string, string> = {
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/webp": ".webp",
};

export function extensionFor(mime: string): string | null {
  return EXTENSIONS[mime] ?? null;
}

export function mediaTypeFor(file: string): "image/jpeg" | "image/png" | "image/webp" {
  if (file.endsWith(".png")) return "image/png";
  if (file.endsWith(".webp")) return "image/webp";
  return "image/jpeg";
}

export function newId(): string {
  return randomUUID();
}

/**
 * Guards a caller-supplied name before it becomes a file path or an object key.
 *
 * Narrow on purpose: ids and image names are ours, generated by `randomUUID`, so
 * anything outside that alphabet is a request to reach somewhere it should not.
 */
function safeName(name: string): string | null {
  return /^[A-Za-z0-9._-]+$/.test(name) && !name.includes("..") ? name : null;
}

// ---- local backend ---------------------------------------------------------

const ROOT = resolve(process.env.SITEWIREAI_STORE ?? join(HERE, "..", "data"));
const IMAGES = join(ROOT, "images");
const PHOTOS = join(ROOT, "photos");

/** The training build wrote here. Still read so the old corpus keeps listing. */
const LEGACY_PHOTOS = join(ROOT, "samples");

// ---- aws backend -----------------------------------------------------------

let docClient: DynamoDBDocumentClient | null = null;
let s3Client: S3Client | null = null;

function documents(): DynamoDBDocumentClient {
  if (!docClient) {
    docClient = DynamoDBDocumentClient.from(new DynamoDBClient({}), {
      // Undefined is how this app spells "no value"; without this every optional
      // field would have to be stripped by hand before every write.
      marshallOptions: { removeUndefinedValues: true },
    });
  }
  return docClient;
}

function s3(): S3Client {
  if (!s3Client) s3Client = new S3Client({});
  return s3Client;
}

// ---- the interface ---------------------------------------------------------

export function storeLocation(): string {
  return usingAws() ? `dynamodb://${TABLE} + s3://${BUCKET}` : ROOT;
}

export async function openStore(): Promise<void> {
  if (usingAws()) return; // Both resources are created by Terraform, not by us.
  await mkdir(IMAGES, { recursive: true });
  await mkdir(PHOTOS, { recursive: true });
}

export async function listPhotos(): Promise<Photo[]> {
  const photos: Photo[] = [];

  if (usingAws()) {
    // A Scan is the right call at this scale — the whole point of the library is
    // "show me everything", and paginating a query by a partition key we would
    // have had to invent would be more machinery for the same answer.
    let cursor: Record<string, unknown> | undefined;
    do {
      const page = await documents().send(
        new ScanCommand({ TableName: TABLE, ExclusiveStartKey: cursor }),
      );
      for (const item of page.Items ?? []) {
        const parsed = parsePhoto(item);
        if (parsed) photos.push(parsed);
      }
      cursor = page.LastEvaluatedKey;
    } while (cursor);
  } else {
    for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
      if (!existsSync(dir)) continue;
      for (const file of await readdir(dir)) {
        if (!file.endsWith(".json")) continue;
        try {
          const parsed = parsePhoto(JSON.parse(await readFile(join(dir, file), "utf8")));
          if (parsed && !photos.some((p) => p.id === parsed.id)) photos.push(parsed);
        } catch {
          // A hand-edited file that no longer parses should not take the whole
          // library down. Skip it; the rest still lists.
        }
      }
    }
  }

  return photos.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getPhoto(id: string): Promise<Photo | null> {
  const name = safeName(id);
  if (!name) return null;

  if (usingAws()) {
    const result = await documents().send(new GetCommand({ TableName: TABLE, Key: { id: name } }));
    return result.Item ? parsePhoto(result.Item) : null;
  }

  for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
    const path = join(dir, `${name}.json`);
    if (!existsSync(path)) continue;
    try {
      return parsePhoto(JSON.parse(await readFile(path, "utf8")));
    } catch {
      return null;
    }
  }
  return null;
}

export async function putPhoto(photo: Photo): Promise<void> {
  const name = safeName(photo.id);
  if (!name) throw new Error(`refusing to write a photo with an unusable id: ${photo.id}`);

  if (usingAws()) {
    await documents().send(new PutCommand({ TableName: TABLE, Item: photo }));
    return;
  }
  await writeFile(join(PHOTOS, `${name}.json`), JSON.stringify(photo, null, 2), "utf8");
}

export async function deletePhoto(id: string): Promise<boolean> {
  const name = safeName(id);
  if (!name) return false;

  const photo = await getPhoto(id);
  if (!photo) return false;

  const image = safeName(photo.imageFile);

  if (usingAws()) {
    await documents().send(new DeleteCommand({ TableName: TABLE, Key: { id: name } }));
    if (image) {
      await s3().send(new DeleteObjectCommand({ Bucket: BUCKET, Key: `images/${image}` }));
    }
    return true;
  }

  for (const dir of [PHOTOS, LEGACY_PHOTOS]) {
    const path = join(dir, `${name}.json`);
    if (existsSync(path)) await unlink(path);
  }
  if (image && existsSync(join(IMAGES, image))) await unlink(join(IMAGES, image));
  return true;
}

export async function writeImage(file: string, bytes: Buffer): Promise<void> {
  const name = safeName(file);
  if (!name) throw new Error(`refusing to write an image with an unusable name: ${file}`);

  if (usingAws()) {
    await s3().send(
      new PutObjectCommand({
        Bucket: BUCKET,
        Key: `images/${name}`,
        Body: bytes,
        ContentType: mediaTypeFor(name),
      }),
    );
    return;
  }
  await writeFile(join(IMAGES, name), bytes);
}

export async function readImage(file: string): Promise<Buffer | null> {
  const name = safeName(file);
  if (!name) return null;

  if (usingAws()) {
    try {
      const result = await s3().send(
        new GetObjectCommand({ Bucket: BUCKET, Key: `images/${name}` }),
      );
      const bytes = await result.Body?.transformToByteArray();
      return bytes ? Buffer.from(bytes) : null;
    } catch {
      return null;
    }
  }

  const path = join(IMAGES, name);
  if (!existsSync(path)) return null;
  try {
    return await readFile(path);
  } catch {
    return null;
  }
}

/**
 * Where the browser should fetch this image from.
 *
 * Locally that is a path this server serves. On AWS it is a presigned S3 URL, so
 * the bytes travel straight from S3 to the browser and never pass through the
 * Lambda's 6 MB response limit. Fifteen minutes is longer than anyone spends on a
 * page and short enough that a copied URL stops working before it spreads.
 */
export async function imageUrl(file: string): Promise<string> {
  const name = safeName(file);
  if (!name) return "";

  if (usingAws()) {
    try {
      return await getSignedUrl(
        s3(),
        new GetObjectCommand({ Bucket: BUCKET, Key: `images/${name}` }),
        { expiresIn: 900 },
      );
    } catch {
      return "";
    }
  }
  return `/images/${name}`;
}
